apiVersion: v1
kind: Service
metadata:
  name: {{ template "registry.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: tomcat
    - port: 5000
      targetPort: 5000
      name: registry
  selector:
    app: {{ template "registry.name" . }}
    release: "{{ .Release.Name }}"

