apiVersion: v1
kind: Service
metadata:
  name: {{ template "infors.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: userport
    - port: 8060
      targetPort: 8060
      name: adminport
  selector:
    app: {{ template "infors.name" . }}
    release: "{{ .Release.Name }}"

