apiVersion: v1
kind: Service
metadata:
  name: {{ template "git.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ template "git.name" . }}
    release: "{{ .Release.Name }}"

