apiVersion: v1
kind: Service
metadata:
  name: {{ template "owncloud.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
{{- if .Values.nodePort.port }}
      nodePort: {{ .Values.nodePort.port }}
{{- end }}
  selector:
    app: {{ template "owncloud.name" . }}
    release: "{{ .Release.Name }}"

